apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: first-app
  template:
    metadata:
      labels:
        app: first-app
    spec:
      containers:
      - name: first-container
        image: ${{ secrets.DOCKER_USERNAME }}/nature-frontend-client:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: first-service
spec:
  selector:
    app: first-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

