name: Deploy to Kubernetes

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'main'  # Default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Helm
        run: |
         wget https://get.helm.sh/helm-v3.14.0-linux-amd64.tar.gz
         tar -zxvf helm-v3.14.0-linux-amd64.tar.gz
         sudo mv linux-amd64/helm /usr/local/bin/helm
         helm version

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
         kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
         
      - name: Add Helm repository
        run: helm repo add my-repo nbsnv5p/my-repo


      - name: Configure Docker registry credentials
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Upgrade Helm chart
        run: |
          helm upgrade --install nature-frontend ./mychart --set image.repository=${{ secrets.DOCKER_USERNAME }}/nature-frontend-client,image.tag=latest
      
      - name: Apply Kubernetes manifest
        run: |
          kubectl apply -f ./manifest/manifest.yaml
          

